server:
  host: 0.0.0.0
  port: 8088

mysql:
  user_name: crm
  password: crm
  addr: 127.0.0.1:3306
  dbname: crm
  max_open_conns: 4096
  max_idle_conns: 1024
  conn_max_lifetime: 3600

feed:
  fetch_interval: 300